services:
  # Django web application
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: planpincieux-web
    command: uv run --project /ppcx python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/ppcx/app
      - /home/fioli/storage/fms:/data
      # - fms_data:/data
    ports:
      - "8001:8000"
    env_file:
      - .env

# volumes:
#   fms_data: