# Generated by Django 5.2.3 on 2025-06-19 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glacier_monitoring_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='created_at',
        ),
    ]
