# Generated by Django 5.2.3 on 2025-06-19 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glacier_monitoring_app', '0002_remove_camera_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cameracalibration',
            name='created_at',
        ),
    ]
