# Generated by Django 5.2.3 on 2025-06-19 17:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glacier_monitoring_app', '0003_remove_cameracalibration_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='checksum_md5',
        ),
        migrations.AddField(
            model_name='camera',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cameracalibration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
