# Generated by Django 5.2.3 on 2025-06-19 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glacier_monitoring_app', '0004_remove_image_checksum_md5_camera_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image_height_px',
            new_name='height_px',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='image_width_px',
            new_name='width_px',
        ),
    ]
