# Generated by Django 5.2.3 on 2025-06-19 18:45

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glacier_monitoring_app', '0005_rename_image_height_px_image_height_px_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, dim=3, null=True, srid=32632),
        ),
    ]
