# Generated by Django 5.2.3 on 2025-06-20 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glacier_monitoring_app', '0006_alter_camera_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dicanalysis',
            old_name='reference_image',
            new_name='master_image',
        ),
        migrations.RenameField(
            model_name='dicanalysis',
            old_name='secondary_image',
            new_name='slave_image',
        ),
        migrations.RemoveField(
            model_name='dicanalysis',
            name='analysis_timestamp',
        ),
    ]
