# Generated by Django 5.2.3 on 2025-06-20 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glacier_monitoring_app', '0007_rename_reference_image_dicanalysis_master_image_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dicanalysis',
            name='different_image_paths',
        ),
        migrations.RemoveConstraint(
            model_name='dicanalysis',
            name='unique_image_pair_paths',
        ),
        migrations.RemoveIndex(
            model_name='dicanalysis',
            name='glacier_mon_master__fdd783_idx',
        ),
        migrations.RemoveIndex(
            model_name='dicanalysis',
            name='glacier_mon_slave_i_024d69_idx',
        ),
        migrations.RemoveField(
            model_name='dicanalysis',
            name='master_image_path',
        ),
        migrations.RemoveField(
            model_name='dicanalysis',
            name='slave_image_path',
        ),
        migrations.RemoveField(
            model_name='dicresult',
            name='status_flag',
        ),
        migrations.AddField(
            model_name='dicresult',
            name='displacement_magnitude_px',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='dicanalysis',
            index=models.Index(fields=['master_image'], name='glacier_mon_master__e88802_idx'),
        ),
        migrations.AddIndex(
            model_name='dicanalysis',
            index=models.Index(fields=['slave_image'], name='glacier_mon_slave_i_5e289e_idx'),
        ),
        migrations.AddConstraint(
            model_name='dicanalysis',
            constraint=models.CheckConstraint(condition=models.Q(('master_timestamp', models.F('slave_timestamp')), _negated=True), name='different_timestamps'),
        ),
        migrations.AddConstraint(
            model_name='dicanalysis',
            constraint=models.UniqueConstraint(fields=('master_image', 'slave_image'), name='unique_image_pair_paths'),
        ),
    ]
