# Generated by Django 5.2.3 on 2025-06-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glacier_monitoring_app', '0008_remove_dicanalysis_different_image_paths_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dicresult',
            name='unique_seed_point',
        ),
        migrations.RenameField(
            model_name='dicresult',
            old_name='seed_x_ref_px',
            new_name='seed_x_px',
        ),
        migrations.RenameField(
            model_name='dicresult',
            old_name='seed_y_ref_px',
            new_name='seed_y_px',
        ),
        migrations.RemoveField(
            model_name='dicresult',
            name='target_x_sec_px',
        ),
        migrations.RemoveField(
            model_name='dicresult',
            name='target_y_sec_px',
        ),
        migrations.AddField(
            model_name='dicresult',
            name='target_x_px',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dicresult',
            name='target_y_px',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='dicresult',
            constraint=models.UniqueConstraint(fields=('analysis', 'seed_x_px', 'seed_y_px'), name='unique_seed_point'),
        ),
    ]
