# Generated by Django 5.2.3 on 2025-06-20 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glacier_monitoring_app', '0009_remove_dicresult_unique_seed_point_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='dicanalysis',
            name='glacier_mon_master__e88802_idx',
        ),
        migrations.RemoveIndex(
            model_name='dicanalysis',
            name='glacier_mon_slave_i_5e289e_idx',
        ),
        migrations.AlterField(
            model_name='dicanalysis',
            name='master_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_analysis', to='glacier_monitoring_app.image'),
        ),
        migrations.AlterField(
            model_name='dicanalysis',
            name='master_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dicanalysis',
            name='slave_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slave_analysis', to='glacier_monitoring_app.image'),
        ),
        migrations.AlterField(
            model_name='dicanalysis',
            name='slave_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
