# Generated by Django 5.2.3 on 2025-06-20 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glacier_monitoring_app', '0010_remove_dicanalysis_glacier_mon_master__e88802_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicanalysis',
            name='reference_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='dicanalysis',
            index=models.Index(fields=['reference_date'], name='glacier_mon_referen_5f33a7_idx'),
        ),
    ]
