# Generated by Django 5.2.3 on 2025-06-20 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glacier_monitoring_app', '0011_dicanalysis_reference_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dicanalysis',
            name='reference_date',
            field=models.DateTimeField(),
        ),
    ]
