# Generated by Django 5.2.3 on 2025-06-20 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glacier_monitoring_app', '0012_alter_dicanalysis_reference_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dicanalysis',
            name='reference_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
