# Generated by Django 5.2.3 on 2025-06-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppcx_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='camera_name',
            field=models.CharField(max_length=255),
        ),
    ]
