# Generated by Django 5.2.3 on 2025-07-01 12:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ppcx_app", "0002_alter_camera_camera_name"),
    ]

    operations = [
        migrations.RunSQL(
            """
            -- Function to be executed by the trigger
            CREATE OR REPLACE FUNCTION delete_dic_h5_file() RETURNS TRIGGER AS $$
            DECLARE
                cmd text;
                file_exists integer;
            BEGIN
                -- Skip if result_file_path is NULL
                IF OLD.result_file_path IS NULL THEN
                    RETURN OLD;
                END IF;
                
                -- Check if file exists
                SELECT INTO file_exists COUNT(*) FROM pg_stat_file(OLD.result_file_path);
                
                -- If file exists, delete it
                IF file_exists > 0 THEN
                    cmd := 'rm -f ' || quote_literal(OLD.result_file_path);
                    PERFORM pg_exec(cmd);
                END IF;
                
                RETURN OLD;
            EXCEPTION WHEN OTHERS THEN
                -- Log error but don't prevent deletion of the database record
                RAISE NOTICE 'Error deleting file %: %', OLD.result_file_path, SQLERRM;
                RETURN OLD;
            END;
            $$ LANGUAGE plpgsql SECURITY DEFINER;
            
            -- Create the trigger
            DROP TRIGGER IF EXISTS delete_dic_h5_file_trigger ON ppcx_app_dic;
            CREATE TRIGGER delete_dic_h5_file_trigger
            BEFORE DELETE ON ppcx_app_dic
            FOR EACH ROW
            EXECUTE FUNCTION delete_dic_h5_file();
            """,
            # SQL to run when migration is reversed
            """
            DROP TRIGGER IF EXISTS delete_dic_h5_file_trigger ON ppcx_app_dic;
            DROP FUNCTION IF EXISTS delete_dic_h5_file();
            """,
        ),
    ]
