# Generated by Django 5.2.3 on 2025-07-01 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppcx_app', '0003_add_dic_file_delete_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='dic',
            name='use_ensemble_correlation',
            field=models.BooleanField(default=False),
        ),
    ]
