# Generated by Django 5.2.3 on 2025-07-01 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppcx_app', '0004_dic_use_ensemble_correlation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dic',
            name='time_difference_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
