# Generated by Django 5.2.3 on 2025-09-03 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppcx_app', '0005_alter_dic_time_difference_hours'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dic',
            old_name='time_difference_hours',
            new_name='dt_hours',
        ),
    ]
