# Generated by Django 5.2.3 on 2025-09-17 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppcx_app', '0006_rename_time_difference_hours_dic_dt_hours'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dic',
            name='unique_image_pair_paths',
        ),
        migrations.AddConstraint(
            model_name='dic',
            constraint=models.UniqueConstraint(fields=('master_image', 'slave_image', 'dt_hours'), name='unique_image_pair_paths_dt_hours'),
        ),
    ]
