# Generated by Django 5.2.3 on 2025-09-17 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppcx_app', '0007_remove_dic_unique_image_pair_paths_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dic',
            name='label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
