# Generated by Django 5.2.3 on 2025-10-14 09:50

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppcx_app', '0008_dic_label_image_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collapse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=0)),
                ('area', models.FloatField(blank=True, null=True)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collapses', to='ppcx_app.image')),
            ],
            options={
                'db_table': 'ppcx_app_collapse',
            },
        ),
    ]
