# Generated by Django 5.2.3 on 2025-10-14 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppcx_app', '0009_collapse'),
    ]

    operations = [
        migrations.AddField(
            model_name='collapse',
            name='centroid',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
