# Generated by Django 5.2.3 on 2025-10-14 10:02

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppcx_app', '0010_collapse_centroid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collapse',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=0),
        ),
    ]
