# Generated by Django 5.2.3 on 2025-10-14 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppcx_app', '0011_alter_collapse_geom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='camera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ppcx_app.camera'),
        ),
    ]
